### ISSUE TITLE
Why does the PineTab 2 recipe use Danct12's fork of pmaports?

### ISSUE THREAD

**Issue by Newbytee** [RoseBlume/PostmarketOS-Lomiri-Images#2]
Hi!

Looking at the PineTab 2 workflow, it seems to be using Danct12's fork of pmaports: https://github.com/RoseBlume/PostmarketOS-Lomiri-Images/blob/e5aea6f3cd59b7f3601d1dc6efe09a85046775c0/.github/workflows/pinetab2.yml#L33

Why is this? The PineTab 2 is available in upstream pmaports now and has been for a good while.

**Comment by RoseBlume** [comment]
I couldnt find it within the feature/lomiri branch. I have found it within the master branch and I intend to update the workflow when I get the wifi working out of box.

**Comment by Newbytee** [comment]
> I couldnt find it within the feature/lomiri branch.

I rebased it now, so this won't be an issue any more.

> I have found it within the master branch and I intend to update the workflow when I get the wifi working out of box

For me, the WiFi works most of the time if I choose iwd instead of wpa_supplicant. Sometimes it takes a reboot or two.

**Comment by RoseBlume** [comment]
I have the wifi itself working but the graphical network login isnt working yet
